### ISSUE TITLE
希望作者能完善一下 401的处理    

### ISSUE THREAD

**Issue by supermebing** [yuexunshi/flutter_demo#1]
case 401:
                {
                  String csrfToken;
                  RequestOptions options = error.response.request;
                  LogUtil.e('未认证异常:$error.response.statusCode');
                  Dio dio = Http.dio;
                  if (csrfToken != options.headers["Authorization"]) {
                    options.headers["Authorization"] = csrfToken;
                    //repeat
                    dio.request(options.path, options: options);
                  }
                  dio.lock();
                  dio.interceptors.responseLock.lock();
                  dio.interceptors.errorLock.lock();
                  refreshtoken().then((reftoken) {
                    options.headers["Authorization"] =
                        csrfToken = 'Bearer ' + reftoken;
                  }).whenComplete(() {
                    dio.unlock();
                    dio.interceptors.responseLock.unlock();
                    dio.interceptors.errorLock.unlock();
                  }).then((e) {
                    //repeat
                    dio.request(options.path, options: options);
                  });
                  return UnauthorisedException(errCode, "没有权限");
                }
                break;

这样写会有问题  报错
flutter: DioError===: -1type 'Future<dynamic>' is not a subtype of type 'FutureOr<Response<dynamic>>'
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: DioError [DioErrorType.RESPONSE]:

**Comment by hongjia888** [comment]
unknownRoute: GetPage(name: '/notfound', page: () => UnknownRoutePage()),

**Comment by yuexunshi** [comment]
> unknownRoute: GetPage(name: '/notfound', page: () => UnknownRoutePage()),

已更新 dio_new
