### ISSUE TITLE
我clone了项目，在dio部分出现了问题

### ISSUE THREAD

**Issue by H-Bin** [yuexunshi/flutter_demo#14]
不添加缓存拦截器，可以正常收发消息
I/flutter ( 5272): *** Request ***
I/flutter ( 5272): uri: http://192.168.1.211:9999/mock/91/dio/categories
I/flutter ( 5272): method: GET
I/flutter ( 5272): responseType: ResponseType.json
I/flutter ( 5272): followRedirects: true
I/flutter ( 5272): connectTimeout: 30000
I/flutter ( 5272): sendTimeout: 0
I/flutter ( 5272): receiveTimeout: 30000
I/flutter ( 5272): receiveDataWhenStatusError: true
I/flutter ( 5272): extra: {refresh: false, noCache: true, cacheKey: null, cacheDisk: false}
I/flutter ( 5272): headers:
I/flutter ( 5272):  Authorization: Bearer
I/flutter ( 5272):
I/flutter ( 5272): *** Response ***
I/flutter ( 5272): uri: http://192.168.1.211:9999/mock/91/dio/categories
I/flutter ( 5272): statusCode: 200
I/flutter ( 5272): headers:
I/flutter ( 5272):  connection: keep-alive
I/flutter ( 5272):  content-type: application/json; charset=utf-8
I/flutter ( 5272):  access-control-allow-credentials: true
I/flutter ( 5272):  date: Fri, 17 Sep 2021 07:06:43 GMT
I/flutter ( 5272):  access-control-allow-origin: undefined
I/flutter ( 5272):  content-length: 508
I/flutter ( 5272):
I/flutter ( 5272): 3          (这里可以正常输出接受data长度)

添加了拦截器之后就没有response了，调试器显示已经执行完毕，但是没有报错，页面也不会输出data长度
I/flutter ( 5272): *** Request ***
I/flutter ( 5272): uri: http://192.168.1.211:9999/mock/91/dio/categories
I/flutter ( 5272): method: GET
I/flutter ( 5272): responseType: ResponseType.json
I/flutter ( 5272): followRedirects: true
I/flutter ( 5272): connectTimeout: 30000
I/flutter ( 5272): sendTimeout: 0
I/flutter ( 5272): receiveTimeout: 30000
I/flutter ( 5272): receiveDataWhenStatusError: true
I/flutter ( 5272): extra: {refresh: false, noCache: true, cacheKey: null, cacheDisk: false}
I/flutter ( 5272): headers:
I/flutter ( 5272):  Authorization: Bearer
I/flutter ( 5272):

数据是我自己在yapi上模拟的

**Comment by yuexunshi** [comment]
demo增加了自定义的cache，并且启用系统cache。

**Comment by H-Bin** [comment]
我仔细看了下大佬的代码，找到了我自己电脑上flutter_dio缓存不能生效的原因，第一次请求进来时，onRequest在本地找不到缓存，所以**var ob = cache[key];** 这里ob永远是null，执行到最后也没有放行，拦截器就拦截了请求，我在onRequest这里加了**handler.next(options);**放行第一次请求，之后请求再进来的时候就正常了。我看别人不加这一句也能成功。有跟我一样情况的这个也许有点帮助。
```
import 'dart:collection';

import 'package:dio/dio.dart';
import 'package:flutter_news/common/utils/storage.dart';
import 'package:flutter_news/common/values/values.dart';

class CacheObject {
  CacheObject(this.response)
      : timeStamp = DateTime.now().millisecondsSinceEpoch;
  Response response;
  int tionmeStamp;

  @override
  bool operator ==(other) {
    return response.hashCode == other.hashCode;
  }

  @override
  int get hashCode => response.realUri.hashCode;
}

class NetCacheInterceptor extends Interceptor {
  // 为确保迭代器顺序和对象插入时间一致顺序一致，我们使用LinkedHashMap
  var cache = LinkedHashMap<String, CacheObject>();

  @override
  onRequest(RequestOptions options, RequestInterceptorHandler handler) async {
    if (!CACHE_ENABLE) return handler.next(options);

    // refresh标记是否是刷新缓存
    bool refresh = options.extra["refresh"] == true;

    // 是否磁盘缓存
    bool cacheDisk = options.extra["cacheDisk"] == true;

    // 如果刷新，先删除相关缓存
    if (refresh) {
      // 删除uri相同的内存缓存
      delete(options.uri.toString());

      // 删除磁盘缓存
      if (cacheDisk) {
        await StorageUtil().remove(options.uri.toString());
      }

      return handler.next(options);
    }

    // get 请求，开启缓存
    if (options.extra["noCache"] != true &&
        options.method.toLowerCase() == 'get') {
      String key = options.extra["cacheKey"] ?? options.uri.toString();

      // 策略 1 内存缓存优先，2 然后才是磁盘缓存

      // 1 内存缓存
      var ob = cache[key];
      if (ob != null) {
        //若缓存未过期，则返回缓存内容
        if ((DateTime.now().millisecondsSinceEpoch - ob.timeStamp) / 1000 <
            CACHE_MAXAGE) {
          return handler.resolve(cache[key]!.response);
        } else {
          //若已过期则删除缓存，继续向服务器请求
          cache.remove(key);
        }
      }

      // 2 磁盘缓存
      if (cacheDisk) {
        var cacheData = StorageUtil().getJSON(key);
        if (cacheData != null) {
          return handler.resolve(
            Response(
              statusCode: 200,
              data: cacheData,
              requestOptions: options,
            ),
          );
        }
      }
    }
    handler.next(options);
  }

  @override
  onError(DioError err, ErrorInterceptorHandler handler) async {
    // 错误状态不缓存
  }

  @override
  onResponse(Response response, ResponseInterceptorHandler handler) async {
    // 如果启用缓存，将返回结果保存到缓存
    if (CACHE_ENABLE) {
      await _saveCache(response);
    }

    handler.next(response);
  }

  Future<void> _saveCache(Response object) async {
    RequestOptions options = object.requestOptions;

    // 只缓存 get 的请求
    if (options.extra["noCache"] != true &&
        options.method.toLowerCase() == "get") {
      // 策略：内存、磁盘都写缓存

      // 缓存key
      String key = options.extra["cacheKey"] ?? options.uri.toString();

      // 磁盘缓存
      if (options.extra["cacheDisk"] == true) {
        await StorageUtil().setJSON(key, object.data);
      }

      // 内存缓存
      // 如果缓存数量超过最大数量限制，则先移除最早的一条记录
      if (cache.length == CACHE_MAXCOUNT) {
        cache.remove(cache[cache.keys.first]);
      }

      cache[key] = CacheObject(object);
    }
  }

  void delete(String key) {
    cache.remove(key);
  }
}
```
但是我电脑上dio_new包的缓存还是没法生效，继续研究下
