### ISSUE TITLE
请问scheduleRequestRetry()返回的Future<Response>，是如何传递给原请求的？

### ISSUE THREAD

**Issue by Vidtion** [yuexunshi/flutter_demo#17]
```
//原请求
dio.get(xxxxx).then((res){
    //1.handle response
}).catchError((e){
    //2。handle error
});
```
下面这个scheduleRequestRetry返回的Future<Response>，如何传递给原请求的`1.handle response`那里
```
Future<Response> scheduleRequestRetry(RequestOptions requestOptions)
```

在demo里没找到示例

**Comment by Vidtion** [comment]
[dio-connectivity-retry-interceptor-flutter-tutorial](https://resocoder.com/2020/03/23/dio-connectivity-retry-interceptor-flutter-tutorial/) 下面的评论有4.0版本的方案

**Comment by yuexunshi** [comment]
> [dio-connectivity-retry-interceptor-flutter-tutorial](https://resocoder.com/2020/03/23/dio-connectivity-retry-interceptor-flutter-tutorial/) 下面的评论有4.0版本的方案

👍🏻👍🏻👍🏻
