### ISSUE TITLE
当接口请求失败的时候报错

### ISSUE THREAD

**Issue by hardgit** [yuexunshi/flutter_demo#18]
I/flutter (23250): Response Text:
I/flutter (23250): {"head":{"code":600,"msg":"您的会话连接超时，请重新登录"}}
I/flutter (23250): 
E/flutter (23250): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'String' is not a subtype of type 'int' of 'index'
E/flutter (23250): #0      DefaultHttpTransformer.parse (package:flutter_river/http/default_http_transformer.dart:8:29)
E/flutter (23250): #1      handleResponse (package:flutter_river/http/http_parse.dart:25:28)
E/flutter (23250): #2      HttpClient.post (package:flutter_river/http/http_client.dart:53:14)
E/flutter (23250): <asynchronous suspension>
![图片](https://user-images.githubusercontent.com/31436497/146319717-7edd48f0-9dc7-44bc-a591-f1acffd34c17.png)

**Comment by yuexunshi** [comment]
类型改成String
