### ISSUE TITLE
在1.26.0版本中启动项目失败

### ISSUE THREAD

**Issue by TakahashiAiko** [yuexunshi/flutter_demo#2]
/D:/Flutter/.pub-cache/hosted/pub.flutter-io.cn/get-3.17.1/lib/get_navigation/src/extension_navigation.dart:1047:3: Error: Type 'ui.Window' not found.
  ui.Window get window => ui.window;
  ^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'D:\Flutter\packages\flutter_tools\gradle\flutter.gradle' line: 997

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\Flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by yuexunshi** [comment]
用2.0
