### ISSUE TITLE
什么时候更新一下dio的版本

### ISSUE THREAD

**Issue by supermebing** [yuexunshi/flutter_demo#5]
什么时候更新一下dio的版本

**Comment by WingCH** [comment]
同求 dio推出了4.0 的更新

**Comment by WingCH** [comment]
我嘗試更新到最新版的dio
https://github.com/yuexunshi/flutter_demo/pull/6

**Comment by lorenzuss** [comment]
什么时候更新啊？5.0

**Comment by yuexunshi** [comment]
> 什么时候更新一下dio的版本

已更新 dio_new

**Comment by yuexunshi** [comment]
> 同求 dio推出了4.0 的更新

已更新 dio_new

**Comment by yuexunshi** [comment]
> 什么时候更新啊？5.0

已更新 dio_new

**Comment by yuexunshi** [comment]
> 我嘗試更新到最新版的dio
> #6

已更新 dio_new
